config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get "static_pages/home"
  get "static_pages/help"

  get '/signout', to: 'sessions#destroy'

  get '/auth/:provider/callback' => 'users#login'
  root to: 'static_pages#home'

  resources :interests, only: [:create, :destroy, :update]
  resources :my_locations, only: [:create, :destroy, :update],controller: 'locations'
  resources :my_badges, only: [:create, :destroy, :update, :like],controller: 'badges'
  resources :pictures do
    collection do
      get :new_upload_form, :pics_edit, :set_default_pic, :set_visible_pic, :import_fb_pictures
    end
  end

  resources :my_badges do
    member do
      get :like, controller: 'badges'
    end
    collection do
      get :badge_list, controller: 'badges'
    end
  end

  resources :users do
    collection do
      get :friends, :page_friends, :autocomplete_location_address, :page_search_criteria, :like_list, :page_like_list, :new_people_around, :page_new_people_around,:crush_list, :date_list, :page_date_list
    end
    member do
      patch :add_location, :badges, :add_testimonial, :add_picture, :map_delete
      get :search_criteria, :likes, :pics_edit, :set_default_pic, :set_visible_pic, :likes_testimonial, :delete_testimonial, :timeline, :crush, :set_godate, :godate
      post :update_status, :update_about_me
    end
  end

  resources :conversations , only: [:show] do
    resources :messages, only: [:create]
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/user.rb
class User 
  include Neo4j::ActiveNode

  property :name, :type => String, :index => :exact
  property :mood, :type => String
  property :status, :type => String
  property :dob, :type => DateTime, :index => :exact
  property :uid, :type => String, :index => :exact, :unique => true
  property :username, :type => String
  property :email, :type => String, :index => :exact
  property :gender, :type => String, :index => :exact
  property :remember_token, :type => String, :index => :exact
  property :fb_access_token, :type => String, :index => :exact
  property :status, :type => String
  property :about_me, :type => String
  property :default_pic, :type => String
  property :godate_status, :type => Boolean, default: false

  scope :gender_filter, ->(g){ where(gender: g)}

  property :friends_list
  serialize :friends_list

  property :pics
  serialize :pics

  property :visible_pictures
  serialize :visible_pictures

  property :fb_pictures
  serialize :fb_pictures


  #before_save :create_remember_token

  validates :email, :uniqueness => true

  has_many :both, :friends,  model_class: User,  rel_class: Friend
  has_many :both, :friend_girls,  model_class: User,  rel_class: Friend_girl
  has_many :both, :friend_boys,  model_class: User,  rel_class: Friend_boy
  has_many :out, :places,  model_class: MyLocation,  rel_class: Place
  has_many :out, :likes, model_class: User,  rel_class: Like
  has_many :out, :crush, model_class: User,  rel_class: Crush
  has_many :out, :godate, model_class: User,  rel_class: GoDate
  #has_many :both, :badges, model_class: User,  rel_class: Badge
  has_many :out, :write_testimonials, model_class: Testimonial,  rel_class: Write_testimonial
  has_many :out, :likes_testimonial, model_class: Testimonial,  rel_class: Like_testimonial
  has_many :in, :testimonials, model_class: Testimonial,  rel_class: My_testimonial
  has_many :out, :pictures,  model_class: Picture,  rel_class: MyPicture
  has_many :out, :userInterests,  model_class: Interest,  rel_class: MyInterest
  #has_one :out, :default_pics,  model_class: Picture,  rel_class: Profile
  has_many :out, :visits,  model_class: User,  rel_class: Visit
  has_many :out, :views,  model_class: User,  rel_class: View
  has_many :out, :add_pic,  model_class: User,  rel_class: Add_pic
  has_many :out, :add_status,  model_class: User,  rel_class: Add_status
  has_many :out, :giveBadges,  model_class: MyBadge,  rel_class: GiveBadge
  has_many :out, :getBadges,  model_class: MyBadge,  rel_class: GetBadge
  has_one :out, :getDetails,  model_class: MyDetail,  rel_class: GetDetail

  #has_one :out, :users_place, type: :users_place, model_class: Location
  #has_n(:friends).to(User).relationship(Friend)
  #has_n(:friend_girls).to(User).relationship(Friend_girl)
  #has_n(:friend_boys).to(User).relationship(Friend_boy)

  def self.create_with_omniauth(auth)
    create! do |user|
      user_details = auth['extra']['raw_info']
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.fb_access_token = auth['credentials']['token']
      user.username = auth['info']['nickname']
      user.email = user_details['email']
      user.gender = user_details['gender']
      #user.dob = DateTime.parse(user_details['birthday'])
      user.remember_token = SecureRandom.urlsafe_base64
    end
  end

  def self.paginate(options={})
    page = options[:page] || 1
    per_page = options[:per_page] || 8
   self.skip((per_page-1) * page).limit(per_page)
  end


 private
  def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
autocomplete :location, :address, :full => true

before_filter :signed_in_user, except: :login 

  def login
    oauth = request.env["omniauth.auth"]
    #@user = User.find_by(uid: oauth['uid'])
    @user = User.find_by(email: oauth['info']['email'])
    #session['fb_auth'] = oauth
    
    if  @user.nil?
      @user = User.create_with_omniauth(oauth)
    # @user = User.find_by(email: oauth['extra']['raw_info']['email'])
    #UserMailer.welcome_email(user).deliver
    end
    
    #@user.fb_access_token = oauth['credentials']['token']
    session['fb_access_token'] = oauth['credentials']['token']
    session['fb_error'] = nil
   # @user.save!
    sign_in @user
    
    
    @graph = Koala::Facebook::API.new(session["fb_access_token"])
    
    if @user.default_pic.nil?
      #@user.pictures =  [] if @user.pictures.nil?
      #@user.visible_pictures = [] if @user.visible_pictures.nil?
      @user.default_pic =  Cloudinary::Uploader.upload(@graph.get_picture(@user.uid,:type => "square", height: 400 , width: 400))["public_id"]
      @picture = Picture.create(pic: @user.default_pic, visible: true)
      MyPicture.create(from_node: @user, to_node: @picture)
      #default_pic = @user.default_pic
      #@user.pictures << default_pic
      #@user.visible_pictures << default_pic
      @user.save!
    end
    
       #@pics = @user.pictures.nil? ? [] : @user.pictures
       #@v_pics = @user.visible_pictures.nil? ? [] : @user.visible_pictures

    
       #@user.pictures = nil
       #@user.visible_pictures = nil
       #@user.save!
   # unless profile_pics.empty?
   #   profile_pics.each do |pic_id|
       # picture =  Cloudinary::Uploader.upload(@graph.get_object(pic_id)["source"])["public_id"]
       # @pics << picture
       # @v_pics << picture
    #  end
    # end

    #    @friends = @graph.get_connections("me", "friends")
    #    @user.friends_list = @friends
    #    @user.save!
        
    #    create_fb_friends(@user.uid, @friends)
    #    sign_in @user
    redirect_to root_path
  end

  def friends
    @friends = []
    unless current_user.gender == 'male'
        #@friends = current_user.friend_boys.paginate(:page => params[:page], :per_page => 8)
        @friends = current_user.friend_boys.limit(8)
    else
        @friends = current_user.friend_girls.limit(8)
    end
  end

  def page_friends
        @friends = []
    unless current_user.gender == 'male'
        @friends = current_user.friend_boys.skip((8) * params[:page].to_i-8).limit(8)
    else
        @friends = current_user.friend_girls.skip((8) * params[:page].to_i-8).limit(8)
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    session['user_name'] = @user.name
    session['user_id'] = params[:id]
    session['user_gender'] = @user.gender
    if @user.uuid == current_user.uuid
      return
    end
    unless @user.uuid == current_user.uuid
      unless  current_user.rels(dir: :outgoing, type: :visits, between: @user).blank?
        rel = current_user.rels(dir: :outgoing, type: :visits, between: @user)
        rel[0].count = rel[0].count + 1
        rel[0].save!
      else
        rel = Visit.new
        rel.from_node = current_user
        rel.to_node = @user
        rel.count = 1
        rel.save!
      end
        current_user.save!
    end
    @my_badges = []

     @req_badges = Neo4j::Session.query.match("(me { uuid: '#{current_user.uuid}' })-[:giveBadges]->(myBadge)<-[:getBadges]-(user { uuid: '#{@user.uuid}' })").where("   myBadge.status = false  ").pluck(:myBadge)
     @badges = Neo4j::Session.query.match("(me { uuid: '#{@user.uuid}' })-[:getBadges]->(myBadge)").where("myBadge.status = true").pluck('DISTINCT myBadge.badgeType, count(myBadge.badgeType)')
     @badges_count = @user.getBadges.where(status: true).count

    @pictures = @user.pictures.where(visible: true)
    @testimonials = @user.testimonials

    unless @user == current_user
      t = []
      @testimonials.each do |testimonial|
        if testimonial.liked
         t << testimonial
         next
        end
        if testimonial.write_testimonials[0] == current_user
         t << testimonial
        end
      end
      @testimonials = t
    end
    unless @user.uuid == current_user.uuid
      @like = current_user.rels(dir: :outgoing, type: :likes, between: @user).blank? ? true : false
    end
    unless @user.uuid == current_user.uuid
      place_ids = current_user.places.map { |p| p.place_id }
      @locations = @user.places.where(place_id: place_ids)
    else
      @locations = @user.places
    end
    @likes_count = @user.rels(dir: :incoming, type: "likes").count

    @interests = @user.userInterests
    @interests_count = @interests.count

    # ip_loc = Geocoder.search(remote_ip)[0]

     # @address = ip_loc.address
     # @latitude = ip_loc.latitude
     # @longitude = ip_loc.longitude

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def autocomplete_location_address
    #gc = Geocoder.search(params[:address])
    @client = GooglePlaces::Client.new('AIzaSyAQ-rZcE4h_upePl7jGYTmt1AKypz3qXPk')
    gc = @client.spots_by_query(params[:address])
    result = gc.collect do |t|
      {value: t.name + ' | ' + t.formatted_address }
    end
    respond_to do |format|
      format.json {render json: result}
    end
  end

  def search_criteria
  @friends = []
    location_ids = params[:location_ids]#.map(&:to_i)
    session['gender_search'] = params[:gender]
    session['location_ids'] = location_ids
    @friends = User.as(:u).places(:l).where(place_id: location_ids).where('u.gender = "' + params[:gender] + '"').limit(2).pluck('DISTINCT u')
    #query = Neo4j::Session.query.match(u: :User, l: :Location)
    #query = query.where('u.id' => current_user.neo_id)  
    #query = query.where('l.neo_id' => location_ids)  
    #@friends = query.where('l.id' => location_ids).pluck('DISTINCT u')
    #@friends = @friends - Array(current_user)
  end

  def page_search_criteria
     @friends = []
    location_ids = session['location_ids']
    gender = session['gender_search']
    @friends = User.as(:u).places(:l).where(place_id: location_ids).where('u.gender = "' + gender + '"').skip((2) * params[:page].to_i-2).limit(2).pluck('DISTINCT u')
   # @friends = @friends - Array(current_user)
  end

  def likes
    @user = User.find(params[:id])
    unless  current_user.rels(dir: :outgoing,type: :likes, between: @user).blank?
      rel = current_user.rels(dir: :outgoing,type: :likes, between: @user)
      rel[0].destroy
     # current_user.save!
    else
      current_user.likes << @user
    #  current_user.save!
    end
    @likes_count = @user.rels(dir: :incoming, type: "likes").count
    #, :content_type => 'text/html'
  end

  def like_list
    @friends = []
    @friends = current_user.likes.limit(2)
  end

  def page_like_list
    @friends = []
    @friends = current_user.likes.skip((2) * params[:page].to_i-2).limit(2)
  end


  def update_status
    @user = current_user
    @user.status = params[:value]
    @user.save!
 
      rel = Add_status.create(from_node: @user, to_node: @user)
      rel.content = params[:value]
      rel.save!

     respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def update_about_me
    current_user.about_me = params[:value]
    current_user.save!

     respond_to do |format|
      format.html
      format.json { render json: current_user }
    end
  end

  def add_testimonial
      @user = User.find(params[:id])
      testimonial = Testimonial.new
      testimonial.say = params[:testimonial]
      testimonial.save!

      rel1 = Write_testimonial.create(from_node: current_user, to_node: testimonial)
      rel1.save!

      rel2 = My_testimonial.create(from_node: testimonial, to_node: @user)
      rel2.save!

      @testimonials = @user.testimonials

      unless @user == current_user
        t = []
        @testimonials.each do |testimonial|
          if testimonial.liked
           t << testimonial
           next
          end
          if testimonial.write_testimonials[0] == current_user
           t << testimonial
          end
        end
        @testimonials = t
      end
  end

  def add_picture
    @user = User.find(params[:id])
    @pictures = []

app/helpers/users_helper.rb
module UsersHelper

  def create_fb_friends(uid, friends)
        friends.each do |friend|
         # FbWorker.perform_async(uid, friend['id'], friend['name'])
        end
  end

end

app/views/users/_crush.html.erb
<% if mutual_crushlike(@user) %>
<% if mutual_crush(@user) %>
<div class="panel-toolbar">
    <h4 class="semibold nm text-danger"><i class="ico-heart mr5"></i>You both have Crush on eachother</h4>
</div>
<br>
<% end %>
<!-- START Crush -->
<% if current_user.rels(dir: :outgoing, type: :crush, between: @user).blank? ? true : false %>
<div class="panel-toolbar">
    <h5 class="semibold nm icon-black-lite"><i class="ico-heart mr5"></i>Do you have a Crush on me?</h5>
</div>
<div class="panel-body pt0 text-center">
   <a href="/users/<%= @user.uuid %>/crush?crush=yes" class="btn btn-success mb5" data-remote="true" >Yes</a>
</div>
<% else %>
<div class="panel-toolbar">
    <h5 class="semibold nm icon-black-lite"><i class="ico-heart mr5"></i>Do you still have a Crush on me?</h5>
</div>
<div class="panel-body pt0 text-center">
   <a href="/users/<%= @user.uuid %>/crush?crush=no" class="btn btn-default mb5" data-remote="true">No</a>
</div>
<% end %>
<!--/ END Crush -->
<% end %>

app/views/users/_godate.html.erb
                          <% unless @user.godate_status? %>
                              <div class="panel-body pt0 text-center">
                                 <a href="/users/<%= @user.uuid %>/set_godate?godate=yes" class="btn btn-success mb5" data-remote="true" >Yes, I'm </a>
                            </div>
                          <% else %>
                            <div class="panel-body pt0 text-center">
                                 <a href="/users/<%= @user.uuid %>/set_godate?godate=no" class="btn btn-success mb5" data-remote="true" >No, I'm not</a>
                            </div>
                          <% end %>

app/views/users/_my_badges.html.erb
 <% unless @uniq_badges.blank? %>
 <div class="">
 	<ul class="list-group mb0">
 	<% @all_badges.each do |k, v| %>
       	<li class="list-group-item">
 		<img src='<%= cloudinary_url( 'crushlike_uvxp3c', :width => 25, :height => 25, :crop => :fit) %>'>
	   <%= "#{k}"  %>
	   <span class="badge"><%= "#{v}"  %></span></li>
	 <% end %>
	</ul>
 </div>
 <% else %>
 	No badges
 <% end %>

app/views/users/_profile_pics.html.erb
                <div class="row" id="shuffle-grid">
                    <% unless @user.pictures.nil? %>
                    <% @user.pictures.each do |pic| %>
                    <div class="col-md-4 " >
                        <!-- thumbnail -->
                        <div class="thumbnail">
                            <!-- media -->
                            <div class="media">
                                <!-- indicator -->
                                <div class="indicator"><span class="spinner"></span></div>
                                <!--/ indicator -->
                                <!-- toolbar overlay -->
                                <div class="overlay">
                                    <div class="toolbar">
                                        <a href="'<%= cloudinary_url(pic, :crop => :fill) %>'" class="btn btn-default magnific" title="view picture"><i class="ico-search"></i></a>
                                        <a href="#" class="btn btn-default" title="love this picture"><i class="ico-heart6"></i></a>
                                        <a href="#" class="btn btn-default" title="Delete"><i class="ico-close"></i></a>
                                    </div>
                                </div>
                                <!--/ toolbar overlay -->
                                <!-- meta -->
                                <span class="meta bottom darken">
                                    <h5 class="nm semibold">
                                        background1.jpg <br/>
                                        <small><i class="ico-calendar2"></i> 2014-01-02</small>
                                    </h5>
                                </span>
                                <!--/ meta -->
                                <img data-toggle="unveil" src="/assets/background/400x400/placeholder.jpg" data-src="<%= cloudinary_url(pic, :width => 175, :height => 200, :crop => :fill) %>" alt="Photo" width="100%" />
                            </div>
                            <!--/ media -->
                        </div>
                        <!--/ thumbnail -->
                    </div>
                    <% end %>
                    <% end %>
                </div>

app/views/users/_show.html.erb
                      <!-- content -->                      
                        <div class="row1">
                          
                         <!-- main col left --> 
                         <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 plr0-sm">
                           
                              <!-- START Widget Panel -->
                         <div class="widget panel bw0-sm mb0 border-radius0-imp">
                            <!-- Thumbnail -->
                            <div class="thumbnail">
                                <!-- media -->
                                <div class="media default_pic" id="default_pic">
                                    <%= render  'users/default_pic' %>
                                </div>
                                <!--/ media -->
                            </div>
                            <!--/ Thumbnail -->
                         </div>
                        <!-- START Widget Panel -->
                         <div class="widget panel bw0-sm bottom-fixed mb0 border-radius0-imp">
                             <!-- meta -->
                                    <span class="meta bottom">
                                        <h4 class="semibold mt10 text-center"><%= current_user.name %>
                                        </h4>
                                    </span>
                            <!--/ meta -->
                            <!-- blockquote -->
                            <div class="m10-p10">
                                
                                <blockquote class="mt5 text-center m0-p10">
                                    <p class="font-15"   >
                                      <a href="#" id="xe_status" data-type="textarea" data-pk="1" class="text-default" ><%= current_user.status %></a>
                                    </p>
                                </blockquote>
                            </div>
                                <!--/ blockquote -->
                                <% @get_details = current_user.getDetails %>
                                <% @get_details = MyDetail.new if @get_details.nil? %>
                            <!-- panel body -->
                            <div class="panel-body pl5 pr5 pt0 pb0">
                                 <!-- Nav section -->
                                <ul class="nav nav-section nav-justified mb5">
                                    <li>
                                        <div class="section">
                                            <h4 class="nm">
                                              <i class="flaticon-add185 icon-grey img-responsive center_block icon-font-30"></i>
                                            </h4>
                                            <h4 class="nm mt5"><%= @get_details.like_count %></h4>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="section">
                                            <h4 class="nm">
                                              <i class="flaticon-medal3 icon-grey img-responsive center_block icon-font-35"></i>
                                            </h4>
                                            <h4 class="nm mt5"><%= @get_details.badge_count %></h4>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="section">
                                            <h4 class="nm">
                                              <i class="flaticon-quill1 icon-grey img-responsive center_block icon-font-35"></i></h4>
                                            <h4 class="nm mt5"><%= @get_details.testimonial_count %></h4>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="section">
                                            <h4 class="nm">
                                              <i class="ico-map-marker icon-grey img-responsive center_block icon-font-35"></i></h4>
                                            <h4 class="nm mt5"><%= @get_details.location_count %></h4>
                                        </div>
                                    </li>                                    
                                    <li class="dis-none-imp">
                                        <div class="section">
                                            <h4 class="nm">
                                              <i class="flaticon-stack21 icon-grey img-responsive center_block icon-font-35"></i></h4>
                                            <h4 class="nm mt5"><%= @get_details.picture_count %></h4>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="section">
                                            <h4 class="nm">
                                              <i class="ico-star icon-grey   img-responsive center_block icon-font-35"></i></h4>
                                            <h4 class="nm mt5"><%= @get_details.interest_count %></h4>
                                        </div>
                                    </li>
                                </ul>
                                <!--/ Nav section -->
                                  <div class="panel panel-minimal nm dis-none">
          
                                      <!-- START Bio -->
                                      <div class="panel-toolbar-wrapper hidden-md hidden-lg">
                                          <div class="panel-toolbar">
                                              <h5 class="semibold nm text-info"><i class="ico-info2 mr5"></i>About me</h5>
                                          </div>
                                      </div>
                                      <div class="panel-body pt0  hidden-md hidden-lg">
                                          <p class="semibold mb5 icon-black">
                                            <a href="#" class="xe_about_me text-default" data-type="textarea" data-pk="1" ><%= current_user.about_me %></a>
                                          </p>
                                          
                                      </div>
                                      <!--/ END Bio -->
                                  </div>
                            </div>
                            <!--/ panel body -->
                        </div>
                        <!--/ END Widget Panel -->
                        </div>
                        </div>


<script>
 
  $("#li_profile").addClass("active");
//  $("#minimize_sidebar_a").click();


    //turn to inline mode
$.fn.editable.defaults.mode = 'inline';

    // user status - xeditable
    // ================================

    $("#xe_status").editable({
        title: "Enter status",
           rows: 5,
           url: '/users/<%= current_user.uuid %>/update_status', 
           ajaxOptions: {
               dataType: 'json' //assuming json response
           },           
           success: function(data, config) {
               if(data && data.id) {  //record created, response like {"id": 2}
                   //set pk
                    //$(this).editable('option', 'pk', data.id);
                   //remove unsaved class
                   $(this).removeClass('editable-unsaved');
                   //show messages
                  // var msg = 'Updated successfully.';
                  // $('#msg').addClass('alert-success').removeClass('alert-error').html(msg).show();
                   $('#save-btn').hide(); 
                   $(this).off('save.newuser');                     
               } else if(data && data.errors){ 
                   //server-side validation error, response like {"errors": {"username": "username already exist"} }
                   config.error.call(this, data.errors);
               }               
           },
           error: function(errors) {
               var msg = '';
               if(errors && errors.responseText) { //ajax error, errors = xhr object
                   msg = errors.responseText;
               } else { //validation error (client-side or server-side)
                   $.each(errors, function(k, v) { msg += k+": "+v+"<br>"; });
               } 
               $('#msg').removeClass('alert-success').addClass('alert-error').html(msg).show();
           }
       });

     $(".xe_about_me").editable({
        title: "Enter status",
           rows: 5,
           url: '/users/<%= current_user.uuid %>/update_about_me', 
           ajaxOptions: {
               dataType: 'json' //assuming json response
           },           
           success: function(data, config) {
               if(data && data.id) {  //record created, response like {"id": 2}
                   //set pk
                    //$(this).editable('option', 'pk', data.id);
                   //remove unsaved class
                   $(this).removeClass('editable-unsaved');
                   //show messages
                  // var msg = 'Updated successfully.';
                  // $('#msg').addClass('alert-success').removeClass('alert-error').html(msg).show();
                   $('#save-btn').hide(); 
                   $(this).off('save.newuser');                     
               } else if(data && data.errors){ 
                   //server-side validation error, response like {"errors": {"username": "username already exist"} }
                   config.error.call(this, data.errors);
               }               
           },
           error: function(errors) {
               var msg = '';
               if(errors && errors.responseText) { //ajax error, errors = xhr object
                   msg = errors.responseText;
               } else { //validation error (client-side or server-side)
                   $.each(errors, function(k, v) { msg += k+": "+v+"<br>"; });
               } 
               $('#msg').removeClass('alert-success').addClass('alert-error').html(msg).show();
           }
       });



</script>                      
        

app/views/users/crush_list.html.erb
 <%= render 'users/list' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Mood</th>
    <th>Status</th>
    <th>Dob</th>
    <th>Uid</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.mood %></td>
    <td><%= user.status %></td>
    <td><%= user.dob %></td>
    <td><%= user.uid %></td>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/likes.js.erb
$(".likes_count").html("<%= @likes_count %>");
$("#crush_div").html("<%= j render 'users/crush' %>");

app/views/users/page_friends.html.erb
<%= render partial: 'users/list' %>

app/views/users/search_criteria.js.erb
$("#main_container").html("<%= j render partial: 'search_criteria' %>");
$("#search_modal").modal('hide');