config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get "static_pages/home"
  get "static_pages/help"

  get '/signout', to: 'sessions#destroy'

  get '/auth/:provider/callback' => 'users#login'
  root to: 'static_pages#home'

  resources :interests, only: [:create, :destroy, :update]
  resources :my_locations, only: [:create, :destroy, :update],controller: 'locations'
  resources :my_badges, only: [:create, :destroy, :update, :like],controller: 'badges'
  resources :pictures do
    collection do
      get :new_upload_form, :pics_edit, :set_default_pic, :set_visible_pic, :import_fb_pictures
    end
  end

  resources :my_badges do
    member do
      get :like, controller: 'badges'
    end
    collection do
      get :badge_list, controller: 'badges'
    end
  end

  resources :users do
    collection do
      get :friends, :page_friends, :autocomplete_location_address, :page_search_criteria, :like_list, :page_like_list, :new_people_around, :page_new_people_around,:crush_list, :date_list, :page_date_list
    end
    member do
      patch :add_location, :badges, :add_testimonial, :add_picture, :map_delete
      get :search_criteria, :likes, :pics_edit, :set_default_pic, :set_visible_pic, :likes_testimonial, :delete_testimonial, :timeline, :crush, :set_godate, :godate
      post :update_status, :update_about_me
    end
  end

  resources :conversations , only: [:show] do
    resources :messages, only: [:create]
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/views/layouts/_checkbox_places.html.erb
                                        <% current_user.places.each do |location| %>
                                          <li class="no-decor mb5">
                                            <span class="checkbox custom-checkbox custom-checkbox-inverse">
                                                <%= check_box_tag 'location_ids[]', location.place_id , true, :id => "location_ids_#{location.id}" %>
                                                <label for="location_ids_<%= location.id %>">&nbsp;&nbsp;<%= location.address %></label>
                                            </span>
                                          </li>
                                        <% end %>

app/views/layouts/_header.html.erb
              <!-- START Template Header -->
        <header id="header" class="navbar navbar-fixed-top">
            <!-- START navbar header -->
            <div class="navbar-header">
                <!-- Brand -->
                <a class="navbar-brand" href="javascript:void(0);">
                    <!-- <span class="logo-figure"></span> -->
                    <span class="logo-text"></span>
                </a>
                <!--/ Brand -->
            </div>
            <!--/ END navbar header -->

            <!-- START Toolbar -->
            <div class="navbar-toolbar clearfix">
                <!-- START Left nav -->
                <ul class="nav navbar-nav navbar-left">
                    <!-- Sidebar shrink -->
                    <li class="hidden-xs hidden-sm">
                        <a href="javascript:void(0);" class="sidebar-minimize" data-toggle="minimize" title="Minimize sidebar">
                            <span class="meta">
                                <span class="icon"></span>
                            </span>
                        </a>
                    </li>
                    <!--/ Sidebar shrink -->

                    <!-- Offcanvas left: This menu will take position at the top of template header (mobile only). Make sure that only #header have the `position: relative`, or it may cause unwanted behavior -->
                    <li class="navbar-main hidden-lg hidden-md hidden-sm">
                        <a href="javascript:void(0);" data-toggle="sidebar" data-direction="ltr" rel="tooltip" title="Menu sidebar" id="minimize_sidebar_a">
                            <span class="meta">
                                <span class="icon"><i class="ico-paragraph-justify3"></i></span>
                            </span>
                        </a>
                    </li>
                    <!--/ Offcanvas left -->

                   

                    <!-- Search form toggler  -->
                    <li class="li-search">
                        <a href="javascript:void(0);" data-toggle="modal" data-target="#search_modal">
                            <span class="meta">
                                <span class="icon"><i class="ico-search"></i></span>
                            </span>
                        </a>
                    </li>
                    <!--/ Search form toggler -->
                </ul>
                <!--/ END Left nav -->

                <!-- START navbar form -->
                <div class="navbar-form navbar-left dropdown" id="dropdown-form">
                    <form role="search">
                        
                        <div class="has-icon">
                            <button class="btn btn-teal mt0 mb0 form-control-btn btn-outline" data-toggle="modal" data-target="#search_modal">Criteria</button>
                            <input type="text" class="form-control" placeholder="Search application...">
                            
                            <i class="ico-search form-control-icon"></i>
                        </div>
                    </form>
                                        <!-- search modal -->
                </div>
                <!-- START navbar form -->

                <!-- START Right nav -->
                <ul class="nav navbar-nav navbar-right hide-sm">
                    <!-- Profile dropdown -->
                    <li class="dropdown profile">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="meta">
                                <span class="avatar"><img src="<%= cloudinary_url( current_user.default_pic, :width => 30, :height => 30, :crop => :fill, :gravity => :faces) %>" class="img-circle" alt="" /></span>
                                <span class="text hidden-xs hidden-sm pl5"><%= current_user.name %></span>
                                <span class="caret"></span>
                            </span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="pa15">
                                <h5 class="semibold hidden-xs hidden-sm">
                                    <p class="nm">60%</p>
                                    <small class="text-muted">Profile complete</small>
                                </h5>
                                <h5 class="semibold hidden-md hidden-lg">
                                    <p class="nm"><%= current_user.name %></p>
                                    <small class="text-muted">60% Profile complete</small>
                                </h5>
                                <div class="progress progress-xs nm mt10">
                                    <div class="progress-bar progress-bar-warning" style="width: 60%">
                                        <span class="sr-only">60% Complete</span>
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li><a href="javascript:void(0);"><span class="icon"><i class="ico-user-plus2"></i></span> My Accounts</a></li>
                            <li><a href="javascript:void(0);"><span class="icon"><i class="ico-cog4"></i></span> Profile Setting</a></li>
                            <li><a href="javascript:void(0);"><span class="icon"><i class="ico-question"></i></span> Help</a></li>
                            <li class="divider"></li>
                            <li data-no-turbolink><a href="<%= signout_path %>" id="fb_signout" class="sign_out_fb" ><span class="icon"><i class="ico-exit"></i></span> Sign Out</a></li>
                        </ul>
                    </li>
                    <!-- Profile dropdown -->

                    <!-- Offcanvas right This menu will take position at the top of template header (mobile only). Make sure that only #header have the `position: relative`, or it may cause unwanted behavior -->
                    <li class="navbar-main dis-none-imp">
                        <a href="javascript:void(0);" data-toggle="sidebar" data-direction="rtl" rel="tooltip" title="Feed / contact sidebar">
                            <span class="meta">
                                <span class="icon"><i class="ico-users3"></i></span>
                            </span>
                        </a>
                    </li>
                    <!--/ Offcanvas right -->
                </ul>
                <!--/ END Right nav -->
            </div>
            <!--/ END Toolbar -->
        </header>
        <!--/ END Template Header -->
       
          <%= form_for([:search_criteria, current_user] , remote: true,  method: :get)  do %>
            <!-- START modal-lg -->
                <div id="search_modal" class="modal fade">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header text-center">
                                <button type="button" class="close" data-dismiss="modal">×</button>
                                  <h3 class="semibold modal-title text-primary">Search</h3>
                                <p class="text-muted">Set the criteria to search</p>
                            </div>
                            <div class="modal-body">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label font-18">Gender</label>
                                        <div class="col-sm-10 pl20 ml20" >
                                            <span class=" custom-radio custom-radio-primary mr15">  
                                                <input type="radio" id="genderradio1" value="male" name="gender" <%= current_user.gender == 'female' ? 'checked' : '' %> >  
                                                <label for="genderradio1">&nbsp;&nbsp;Male</label>   
                                            </span>
                                            <span class=" custom-radio custom-radio-primary">  
                                                <input type="radio" id="genderradio2" value="female" name="gender" <%= current_user.gender == 'male' ? 'checked' : '' %>>  
                                                <label for="genderradio2">&nbsp;&nbsp;Female</label>   
                                            </span>
                                        </div>
                                    <label class="col-sm-12 control-label font-18">Location</label>
                                    <br>
                                      <ul class="" id="ul_places">
                                        <%= render partial: 'layouts/checkbox_places' %>
                                      </ul>
                            </div>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary" id="search_submit">Search</button>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div>
                <!--/ END modal-lg -->

              <% end %>


<script type="text/javascript">
$('input[type="submit"]').click(function(){
  $(this).button('loading');
});
</script>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.2.0/respond.min.js"></script>
     <![endif]-->

app/views/layouts/_sidebar.html.erb
        <!-- START Template Sidebar (Left) -->
        <aside class="sidebar sidebar-left sidebar-menu">
            <!-- START Sidebar Content -->
            <section class="content slimscroll">
                
                <!-- START Template Navigation/Menu -->
                <ul class="topmenu topmenu-responsive sidebar_ul" data-toggle="menu">
                    <li id="li_home" >
                        <a href="<%= new_people_around_users_path %>">
                            <span class="figure"><i class="ico-home2"></i></span>
                            <span class="text">People around</span>
                        </a>
                    </li> 
                    <li id="li_timeline">
                        <a href="<%= timeline_user_path(current_user) %>" title="Timeline">
                            <span class="figure"><i class=" ico-menu6"></i></span>
                            <span class="text">Timeline</span>
                        </a>
                    </li>
                    <li id="li_profile">
                        <a href="/" title="Profile">
                            <span class="figure"><i class="ico-user2"></i></span>
                            <span class="text">My Profile</span>
                        </a>
                    </li>
                    <li id="li_like_list">
                        <a href="<%=  like_list_users_path %>" title="Like List">
                            <span class="figure"><i class="ico-heart-empty"></i></span>
                            <span class="text">My Like list</span>
                        </a>
                    </li>
                    <li id="li_crush_list">
                        <a href="<%=  crush_list_users_path %>">
                            <span class="figure"><i class="ico-heart"></i></span>
                            <span class="text">My Crush list</span>
                        </a>
                    </li>
                    <li id="li_crush_list">
                        <a href="<%=  date_list_users_path %>">
                            <span class="figure"><i class="ico-bubble-heart"></i></span>
                            <span class="text">Date seekers</span>
                        </a>
                    </li>
                    <li id="li_sign_out" data-no-turbolink>
                        <a href="<%= signout_path %>" id="fb_signout" class="sign_out_fb" >
                            <span class="figure"><i class="ico-exit"></i></span>
                            <span class="text">Sign out</span>
                        </a>
                    </li>

                    <li id="li_fb_friends" class="dis-none-imp">
                        <a href="<%= friends_users_path %>" title="Facebook Friends">
                            <span class="figure"><i class="ico-users2"></i></span>
                            <span class="text">Facebook Friends</span>
                        </a>
                    </li>
                    <li id="li_notifications" class="dis-none-imp">
                        <a href="/">
                            <span class="figure"><i class="ico-bell"></i></span>
                            <span class="text">Notifications</span>
                        </a>
                    </li>
                    <li id="li_messages" class="dis-none-imp">
                        <a href="/">
                            <span class="figure"><i class="ico-envelope-alt"></i></span>
                            <span class="text">Messages</span>
                        </a>
                    </li>

                </ul>
                <!--/ END Template Navigation/Menu -->

                <!--/ END Sidebar summary -->
            </section>
            <!--/ END Sidebar Container -->
<script  type="text/javascript">
    $(".sidebar_ul > li").click(function(){
        $(this).parent().children("li").removeClass("active");
        $(this).addClass("active");
        $("#minimize_sidebar_a").click();
    });
</script>
        </aside>
        <!--/ END Template Sidebar (Left) -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="Express yourself landing page.">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %> 
</head>
<body>

<% if signed_in? %>
            
                  <!-- top nav -->
                    <%= render 'layouts/header' %>
                  <!-- /top nav -->
            
                  <!-- sidebar -->
                    <%= render 'layouts/sidebar' %>
                  <!-- /sidebar -->
                
                  
                
                          <!-- START Template Main -->
                            <section id="main" role="main">
                                <!-- START Template Container -->
                                <div id="main_container" class="container-fluid plr0-sm pt0">
                                <div class="indicator main_container_load_indicator"><span class="spinner"></span></div>
                                    <%= yield %>                                    
                                </div>
                                <!--/ END Template Container -->

                                <!-- START To Top Scroller -->
                                <a href="#" class="totop animation" data-toggle="waypoints totop" data-showanim="bounceIn" data-hideanim="bounceOut" data-offset="50%"><i class="ico-angle-up"></i></a>
                                <!--/ END To Top Scroller -->

                            </section>
                          <!--/ END Template Main -->
<div id="fb-root"></div>
              <div id="status"></div>
            
 
<% else %>
  <%= yield %>
<% end %>


</body>
</html>
<script>

  //Turbolinks.enableTransitionCache();

    $('#fb_login').click(function(){
        checkLoginState();
    });
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
    //  testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
 //     document.getElementById('status').innerHTML = 'Please log ' +
   //     'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
    //  document.getElementById('status').innerHTML = 'Please log ' +
      //  'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
        return FB.login(function(response) {
          if (response.authResponse) {
            return window.location = '/auth/facebook/';
          }
        });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '<%= FACEBOOK_CONFIG["FACEBOOK_APP_ID"] %>',
    status     : true,  // check login status
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.1
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

    return $('#fb_signout').click(function(e) {
    FB.getLoginStatus(function(response) {
      if (response.status === 'connected') {
        // the user is logged in and has authenticated your
        // app, and response.authResponse supplies
        // the user's ID, a valid access token, a signed
        // request, and the time the access token 
        // and signed request each expire
        var uid = response.authResponse.userID;
        var accessToken = response.authResponse.accessToken;
      } else if (response.status === 'not_authorized') {
        // the user is logged in to Facebook, 
        // but has not authenticated your app
      } else {
        // the user isn't logged in to Facebook.
      }
        return FB.logout(); 
   });
    return true;
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }

       $('body').on('click', '.images_div', function(){
        $(".profile_pics").magnificPopup({
              type: "image",
              gallery: {
                  enabled: true
              }
          }).magnificPopup('open');

       
        
      });

$('.main_container_load_indicator').removeClass('show');
$('.main_container_load_indicator_show').click(function(){
  $('.main_container_load_indicator').addClass('show');
});
</script>